config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'

  namespace :api do
      resources :users, only: [] do
        resources :posts, only: [:index] do
          resources :comments, only: [:index, :create]
        end
      end
    end

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    confirmations: 'users/confirmations'
  }

  root "users#index"
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :comments, only: [:new, :create, :destroy]
      resources :likes, only: [:new, :create]
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: :author_id
  has_many :likes, foreign_key: :post_id, dependent: :destroy
  has_many :comments, foreign_key: :post_id, dependent: :destroy

  validates :title, presence: true, length: { maximum: 250 }
  validates :text, presence: true
  after_create :increment_post_counter
  before_destroy :decrement_post_counter

  before_destroy :delete_associated_comments_and_likes

  def delete_associated_comments_and_likes
    comments.destroy_all
    likes.destroy_all
  end

  def recent_comments
    comments.order(created_at: :desc).limit(5)
  end

  def increment_post_counter
    author.increment!(:post_counter)
  end

  def decrement_post_counter
    author&.decrement!(:post_counter)
  end
end

app/controllers/api/posts_controller.rb
class Api::PostsController < ApplicationController
  def index
    posts = User.find(params['user_id']).posts

    render json: posts
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: %i[create destroy]

  load_and_authorize_resource

  def index
    @users = User.find(params[:user_id])
    @user = User.find(params[:user_id])

    @posts = @users.posts
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @author = User.find(params[:user_id])
    @post = @author.posts.new(post_params)

    if @post.save
      redirect_to user_path(id: @post.author_id)
    else
      render :new, alert: 'An error has occurred while creating the post'
    end
  end

  def post_params
    params.require(:post).permit(:title, :text)
  end

  def destroy
    @post.destroy
    redirect_to user_posts_path, notice: 'Post was successfully deleted.'
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/index.html.erb
<main>
  <section>
    <div class="card pagination">
      <div class="user-image border">
        <%= image_tag(@user.photo, class: "add-css-class") %>
      </div>
      <div class="user-data border">
        <h1><%= @user.name %></h1>
        <% if current_user %>
          <%= link_to "Add a post",new_user_post_path(@user), method: :get, class: "btn right" %>
        <% end %>
      </div>
    </div>
  </section>
  <section>
    <ul>
      <% @posts.each do |post| %>
        <%= link_to user_post_path(user_id: post.author_id, id: post.id) do %>
          <li class="card hover column">
            <div class="card column">
              <h2><%= post.title %></h2>
              <p><%= post.text %></p>
              <div class="right">
                <span>Comments: <%= post.comments_counter %></span>
                <span>Likes: <%= post.likes_counter %> </span>
              </div>
            </div>
            <div class="commets-container">
              <h4>Comments:</h4>
              <ul>
                <% post.recent_comments.each do |comment| %>
                  <p><%= comment.author.name %>: <%= comment.text %></p>
                <% end %>
              </ul>
            </div>
          </li>
        <% end %>
      <% end %>
    </ul>
  </section>
</main>

app/views/posts/new.html.erb
<main>
  <h1>Add a new post</h1>
  <%= form_with model: @post, url: user_posts_path, class: "form" do |form| %>
    <%= form.label :title %> <br>
    <%= form.text_field :title %> <br>
    <%= form.label :text %> <br>
    <%= form.text_area :text , cols: 30, rows: 10 %> <br>
    <%= form.submit "Submit", class: "btn" %>
  <% end %>
</main>

app/views/posts/show.html.erb
<main>
  <section class="card column">
    <div class="card column">
      <h2><%= @post.title %></h2>
      <p><%= @post.text %></p>
      <div class="right">
        <span>Comments: <%= @post.comments_counter %></span>
        <span>Likes: <%= @post.likes_counter %> </span>
      </div>
      <div class="button_field">
      <% if user_signed_in? %>
        <%= link_to "Comment", new_user_post_comment_path(user_id: @post.author_id, post_id: @post.id ), class: "btn" %>
        <%= form_with model: @like, url: user_post_likes_path(post_id: @post.id) do |form| %>
          <%= form.submit "Like", class: "btn" %>
        <% end %>
        <% if can? :destroy, @post %>
          <%= button_to "Delete post", user_post_path(user_id: @post.author.id, post_id: @post.id), method: :delete, class: "btn"  %>
        <% end %>
      <% end %>
      </div>
    </div>
    <div class="commets-container">
      <h4>Comments:</h4>
      <ul>
        <% @post.comments.includes(:author).includes(:post).each do |comment| %>
        <li>
          <p><%= comment.author.name %>: <%= comment.text %></p>
          <% if can? :destroy, comment %>
            <%= button_to "Delete", user_post_comment_path(user_id: comment.author.id, post_id: comment.post.id, id: comment.id), method: :delete, class: "btn"  %>
          <% end %>
        </li>
        <% end %>
      </ul>
    </div>
  </section>
</main>